version: '3.9'

services:
  redis:
    image: redis:7
    container_name: agendamento-redis
    expose:
      - '6379'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agendamento-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=${PORT:-3000}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agendamento-worker
    command: npm run worker
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
